name: Docker Build, Run and Push 
 
on:
  push:

jobs:
    docker:
      runs-on: ubuntu-latest

      permissions:
             contents: read
             packages: write

      steps:
        - name: Code Checkout
          uses: actions/checkout@v4

        - name: Login to GHCR
          uses: docker/login-action@v3
          with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build Image
          run: docker build -t demo-app .

        - name: Run Container
          run: docker run -p 8080:8080 demo-app

        - name: Tag image with timestamp version
          run: |
            VERSION=$(date +'%Y-%m-%d-%H-%M')
            IMAGE=ghcr.io/${{ github.repository_owner }}/demo-app:${VERSION}
            docker tag demo-app $IMAGE
            echo "IMAGE=$IMAGE" >> $GITHUB_ENV
 
        - name: Push image to GHCR
          run: docker push $IMAGE
          env:
            IMAGE: ${{ env.IMAGE }}
               
